### PR TITLE
Added new filters, fixed text domain

### LINKED ISSUE #3: Add filter for post types affected by the plugin
There should be a filter to exclude post types from the plugin’s functionality. 

Example user story: a plugin like [Custom Post Widget](https://wordpress.org/plugins/custom-post-widget/) would implement a CPT, but completely hide its posts from pretty much everywhere. Their content would only be inserted into another post’s, page’s or widget’s content. 
For that type of a CPT the confirm dialogue of PC wouldn’t make any sense, but would rather hinder users in their workflow.

### LINKED ISSUE #5: Use dash for the plugin text domain
From the [WordPress Codex](https://codex.wordpress.org/I18n_for_WordPress_Developers#Text_Domains):

> If your plugin is a single file called my-plugin.php or it is contained in a folder called my-plugin the domain name should be my-plugin. The text domain name must use dashes and not underscores.

Simply put, the text domain should match the plugin folder (`publish-confirm` instead of `publish_confirm`)

### PR DESCRIPTION
**Pull request by glueckpress**
Added 2 new filters (closes #3):

 * `publish_confirm_exclude_post_types` – Checks for an array of post types to be excluded. The confirm message would not appear here.
 * `publish_confirm_include_post_types` – Checks for an array of post types to limit the plugin’s functionality to. The confirm message would _only_ appear here. Has priority above `publish_confirm_exclude_post_types` as it bails out later down the class.

Changed text domain to include a dash instead of underscore. Closes #5.

Bumped version to 0.1, updated README + changelog.

### CODE REVIEW

**Comment by glueckpress** [comment]
This also includes all the administrative updates from https://github.com/pluginkollektiv/publish-confirm/tree/milestone/v0.0.6-administrative-updates. In case this gets merged, the _milestone/v0.0.6-administrative-updates_ branch can be deleted as well.

**Comment by swissspidy** [comment]
Those two filters are quite redundant. If you want to disable this feature for a specific post type, just remove it from the `publish_confirm_include_post_types` array.

The array passed to `publish_confirm_include_post_types` could default to all public post types, i.e. `get_post_types( array( 'public' => true ) )` (post, page, attachment) __\*__. That'd also mean we can remove the `has_filter( 'publish_confirm_include_post_types' )` condition and make the code more simple in general.

\* _Maybe_ without attachments

**Comment by glueckpress** [comment]
@swissspidy Thx, will take a look.

**Comment by glueckpress** [comment]
Meh, backwards compat? :disappointed: 
The plugin includes all post types so far. If we go ahead and limit the default stack, things might break for some users. Although it’s rather unlikely with 400+ active installs. Shall we risk it?

**Comment by swissspidy** [comment]
> The plugin includes all post types so far.

Oh, well then default to `get_post_types()` without any arguments.

**Comment by glueckpress** [comment]
Reverted. :)

**Pull request merged**
